#!/bin/bash

set -e

if [ -n "${DEB_HOST_GNU_TYPE:-}" ]; then
    CROSS_COMPILE=${DEB_HOST_GNU_TYPE}-
else
    CROSS_COMPILE=
fi

${CROSS_COMPILE}gcc -pedantic -Wall -Werror -o test-run debian/tests/simple-build.c $(${CROSS_COMPILE}pkg-config --cflags --libs gpg-error)
./test-run
rm -f test-run
